### ISSUE TITLE
Janitor not finding any media to delete

### ISSUE THREAD

**Issue by marka65** [Anthirian/script.service.janitor#57]
**OS:** Running on QNAP 4.3.3 (Ubuntu 14.04.1 LTS, kernel: Linux x86 64-bit version 4.2.8)
**Python Version:** Python 2.7.13
**Janitor Version:**  4.3.1
**Kodi Version:** 17.1 (Kodi compiled Apr 22 2017 by GCC 4.8.4 for Linux x86 64-bit version 3.13.11)

Currently have only 3 exclusions enabled out of the possible 5

I have attached a summary of the debugging log file.
[JanitorDebugLogSummary.txt](https://github.com/Anthirian/script.service.janitor/files/969635/JanitorDebugLogSummary.txt)

The problem seems to be that when an exclusion is not used, the buildup of the sql string has % added, and so for me there are 2 AND statements that contain the following: 
`AND ((episode_view.strPath NOT  LIKE '%%'))`

Workaround for me was to fill the last 2 empty exclusion locations with duplicate exclusion paths.

**Comment by Anthirian** [comment]
I think I have made a copy and paste mistake when I added two more exclusion options. Could you please check if `default.py` contains the lines below (from line 309 and onwards)?

    (get_setting(exclusion_enabled) and get_setting(exclusion3) is not "", by_exclusion3),
    (get_setting(exclusion_enabled) and get_setting(exclusion3) is not "", by_exclusion4),
    (get_setting(exclusion_enabled) and get_setting(exclusion3) is not "", by_exclusion5)

Please look if you can find the `get_setting(exclusion3)` part for all lines. If so, please correct them so that the numbers match for each line. If you've done that, please try again and tell me if that fixes your problem. If so, I will push an update that fixes this issue for everyone.

**Comment by marka65** [comment]
Yes, that seemes to be the problem

Manually changed the 2 lines to the correct variables for exclusions and modified my settings.xml to remove my duplicate paths and it automatically cleaned as it should.

**Comment by Anthirian** [comment]
Great, thanks for confirming. I'll push a bug release soon. In the meantime you can just keep using the manual fix.
