### ISSUE TITLE
Exclusions being ignored...

### ISSUE THREAD

**Issue by jgrn307** [Anthirian/script.service.janitor#76]
So I've recently moved my media center to a new system, and am using smb to share up the videos.  I have videos in two folders, and I've set one of those folders up as an exclusion (I don't want anything cleaned from there).  I've clearly selected the same smb share I used for the media as the exclusion, but the exclusion is being ignored so its deleting files I don't want.  This is a new behavior -- a few months ago (and a different smb share) it worked fine.  Now I can't use it because I'm losing videos.  Help!  I'm using version 4.4.0 on Libreelec Kodi 9.0.2.

**Comment by Anthirian** [comment]
Could you please show me a debug log so I can investigate better?

**Comment by Anthirian** [comment]
Closing this issue since no input was received

**Comment by mtcdood** [comment]
@Anthirian I don't know if people normally get notifications for closed issues so pinging.

**Comment by Anthirian** [comment]
I'm sorry, it appears that I missed the notifications. Thanks for supplying the debug log. The exclusions checks _are_ there.

```javascript
2019-10-25 04:00:31.693 T:18136   DEBUG: Janitor: [VideoLibrary.GetEpisodes] Filters enabled: [{u'operator': u'greaterthan', u'field': u'playcount', u'value': u'0'}, {u'operator': u'false', u'field': u'inprogress', u'value': u''}, {u'operator': u'doesnotcontain', u'field': u'path', u'value': u'smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/anime$/'}, {u'operator': u'doesnotcontain', u'field': u'path', u'value': u'smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/tv$/Star Trek The Next Generation/'}, {u'operator': u'doesnotcontain', u'field': u'path', u'value': u'smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/tv$/The X-Files/'}]
```

On this line I see Janitor creates a JSON-RPC call to search for videos:
- with a playcount larger than 0 
- that are not currently in progress
- that do not contain `smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/anime$/`
- nor `smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/tv$/Star Trek The Next Generation/`
- and not `smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/tv$/The X-Files/`.

A few lines down we see the results obtained from Kodi with these filters.

```javascript
2019-10-25 04:00:31.867 T:18136   DEBUG: Janitor: JSON Response: {u'episodes': [{u'showtitle': u'Star Trek: The Next Generation', u'episodeid': 737, u'file': u'smb://officedesktop1/tv$/Star Trek The Next Generation/Star Trek TNG Season 01/Star.Trek.The.Next.Generation.S01E10.mp4', u'label': u'1x10. Hide and Q'}], u'limits': {u'start': 0, u'total': 1, u'end': 1}}
```

You can see here that indeed the path to the episode that was matched 
```
smb://officedesktop1/tv$/Star Trek The Next Generation/Star Trek TNG Season 01/Star.Trek.The.Next.Generation.S01E10.mp4
```
does not contain the string 
```
smb://mtcdood:6cm7ajc514gGeov152P-%23pawum@officedesktop1/tv$/Star Trek The Next Generation/
```
because the exclusion path contains a username and password, while Kodi saves the path to the file without the credentials in its internal database.

My advice would be to keep the ways you added the video source and the exclusion folders identical, to make sure the exclusions work correctly.

**Comment by mtcdood** [comment]
Then it's stripping the username and password before checking files for exclusions.

`settings.xml`
```
    <setting id="exclusion1">smb://mtcdood:password@officedesktop1/anime$/</setting>
    <setting id="exclusion2">smb://mtcdood:password@officedesktop1/tv$/Star Trek The Next Generation/</setting>
    <setting id="exclusion3">smb://mtcdood:password@officedesktop1/tv$/The X-Files/</setting>
```

**Comment by mtcdood** [comment]
`sources.xml`
```
            <path pathversion="1">smb://mtcdood:password@officedesktop1/anime$/</path>
```
etc

`settings.xml`
```
    <setting id="exclusion1">smb://mtcdood:password@officedesktop1/anime$/</setting>
```
etc

**Comment by mtcdood** [comment]
Please remove my passwords from these debug log quotes as Github are too much of cunts to do it themselves.
