### ISSUE TITLE
[Feature Request] Delete files only if all profiles have watched the video

### ISSUE THREAD

**Issue by patrickschmelter** [Anthirian/script.service.janitor#83]
My Kodi setup is used by two profiles. Since disk space is getting low way quicker with two people binge watching stuff I'm constantly sitting down and wiping my 9TB disks manually, which kind of sucks on the long term. This add-on seems to be perfect for deleting already watched video files, the only thing holding me from using it is that I couldn't find a way to set it up so that it only deletes files which are marked as watched in all profiles available (or set up). In my case it would work perfectly because I am marking all the stuff I don't mind watching as already watched to keep my library clean and the other person is doing the same.

I would really love to see such a feature :) I have never coded Kodi add-ons, but if somebody would point me the way then I wouldn't mind getting my hands dirty myself and submit a pull request

**Comment by Anthirian** [comment]
Thanks for the suggestion. I can see that it would a be useful feature to have. Unfortunately it is really difficult to realise, since one profile's video database cannot be queried from the other profile's addons. This means that Janitor's view of the video database is limited to the current profile. In order to work with this there would have be some sort of way to make a copy of this database in a file somewhere Janitor could read it from both profiles. This is also really difficult because Janitor is only able to write files to the current user's profile directory. I am afraid this is too much of a hassle to implement right now, unless Team Kodi at some point decide to allow sharing between user profiles. However, if you think of a good way and are able to achieve this, please submit a pull request and I will happily review it.
